---
name: CI

'on':
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:

  yaml-lint:
    name: Run YAML Lint
    uses: ./.forgejo/workflows/run-yaml-lint.yml

  ansible-lint:
    name: Run Ansible Lint
    uses: ./.forgejo/workflows/run-ansible-lint.yml
