---

# resources
# - https://wiki.debian.org/UnattendedUpgrades

- name: Install unattended-upgrades, apt-listchanges
  ansible.builtin.apt:
    name:
      - unattended-upgrades
      - apt-listchanges
    state: present

- name: Activate unattended upgrades (step 1)
  ansible.builtin.shell: >
    set -o pipefail &&
    echo unattended-upgrades unattended-upgrades/enable_auto_updates
    boolean true | debconf-set-selections
  register: debconf_selection
  changed_when: debconf_selection.rc != 0   # todo

- name: Activate unattended upgrades (step 2)
  ansible.builtin.command: >
    dpkg-reconfigure -f noninteractive unattended-upgrades
  register: dpkg_reconfigure
  changed_when: dpkg_reconfigure.rc != 0    # todo

- name: Manually run unattended upgrade
  ansible.builtin.command: unattended-upgrade
  register: unattended_upgrade
  changed_when: unattended_upgrade.rc != 0  # todo
